version: "3.8"

services:
  ci-cd-task-services:
    build: .
    ports:
      - "1323:1323"
    restart: on-failure
    depends_on:
      - mysql-service
    environment:
      - DBHOST=mysql-service
      - DBPORT=3306
      - DBUSER=root
      - DBPASS=password
      - DBNAME=learndocker
    networks:
      - network-test

  mysql-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - network-test

networks:
  network-test:
    driver: bridge