name: Deploy

on: [push]

jobs:
  build-image:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build image
        run: docker build -t wdinx/ci-cd-task:latest .
      - name: login registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push image
        run: docker push wdinx/ci-cd-task:latest


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-to-doplets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/
            docker pull wdinx/ci-cd-task:latest
            docker run -d -p 1325:1323 wdinx/ci-cd-task:latest
#            docker compose down && docker compose up --build -d